INSERT or IGNORE INTO Usuario VALUES ('PAULO','PAULO','1')

INSERT or IGNORE INTO Grupo VALUES('MANTIMENTOS')

INSERT or IGNORE INTO Produto VALUES('ARROZ','KG',15.90,1)

INSERT or IGNORE INTO ListaDespesa VALUES ('MINHA LISTA','2020-06-20',450.00)

INSERT or IGNORE INTO ListaDespesaItem VALUES (1,1,2,15.90,31.80)